export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

//category
export const LOAD_CATEGORY_SUCCESS = "LOAD_CATEGORY_SUCCESS";
export const LOAD_SUBCATEGORY_SUCCESS = "LOAD_SUBCATEGORY_SUCCESS";
export const LOAD_PRODUCT_SUCCESS = "LOAD_PRODUCT_SUCCESS";
export const LOAD_ORDER_SUCCESS = "LOAD_ORDER_SUCCESS";
export const LOAD_SELLER_SUCCESS = "LOAD_SELLER_SUCCESS";
export const LOAD_ADDRESS_SUCCESS = "LOAD_ADDRESS_SUCCESS";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_SINGLE_SUCCESS = "LOAD_SINGLE_SUCCESS";
export const LOAD_SINGLE_PRODUCT_SUCCESS = "LOAD_SINGLE_PRODUCT_SUCCESS";
export const LOAD_CURRENTUSER_SUCCESS = "LOAD_CURRENTUSER_SUCCESS";
